### ISSUE TITLE
Unexpected token  in JSON at position 0

### ISSUE THREAD

**Issue by Cd-corgi** [MenuDocs/erela.js#193] opened 2022-09-01 23:08 UTC
I'm using the `Erela.js v2.3.3` and when i search a song. in the `petitio` npm just throws an error like the tittle one. i reinstalled the npm but still...

**Comment by Cd-corgi** [comment] 2022-09-01 23:09
This is a preview of the error... it redirects me a npm called petitio in this directory `node_modules/petitio/dist/index.js` 

![image](https://user-images.githubusercontent.com/70237066/188027385-be386632-39b1-411e-bb41-21c125253e22.png)

**Comment by melike2d** [comment] 2022-09-01 23:41
Duplicate of #190

**Closed by melike2d** 2022-09-01 23:41 UTC

**Comment by Nytelife26** [comment] 2022-09-04 00:03
If anyone has further information as to the JSON that was failing to be parsed (which shouldn't happen because `JSON.parse` is a Node thing, not ours) I'd appreciate it so even though erela.js doesn't use it anymore we can fix the issue with petitio. Many thanks in advance.
